format = 1
generated = true
name = "Baba Zula"
mbid = "8aefc2cd-c441-4a2a-912f-ae2b9717a865"
spotify = "39zIRxvWFOGGH4hxGqRkLy"
begin = "1996"
origin = "Istanbul"

tags = ["psychedelic", "avant-garde", "dub", "electronica", "tr", "90s"]

tops = [
  "Gerekli Şeyler",
  "Haller Yollar",
  "Carino (feat. La Yegros)",
  "Bir Sana Bir De Bana",
  "Aşıkların Sözü Kalır (feat. Brenna Mac Crimmon)",
]

links = [
  { to = "gaye-su-akyol", type = "similar" },
  { to = "derya-y-ld-r-m-and-grup-im-ek", type = "similar" },
  { to = "alt-n-gun", type = "similar" },
  { to = "lalalar", type = "similar" },
]
