format = 1
generated = true
name = "Black Country, New Road"
mbid = "e9403d9c-329b-4108-a26f-564159d441d9"
spotify = "3PP6ghmOlDl2jaKaH0avUN"
begin = "2018"
origin = "Cambridge"

tags = ["post-rock", "art-rock", "experimental-rock", "chamber-pop", "uk", "2010s"]

tops = [
  "The Place Where He Inserted the Blade",
  "Basketball Shoes",
  "Concorde",
  "Chaos Space Marine",
  "Nancy Tries to Take the Night",
]

links = [
  { to = "racing-mount-pleasant", type = "similar" },
  { to = "cameron-winter", type = "similar" },
  { to = "geese", type = "similar" },
  { to = "black-midi", type = "similar" },
]
