format = 1
generated = true
name = "Godspeed You! Black Emperor"
mbid = "3648db01-b29d-4ab9-835c-83f6a5068fe4"
spotify = "4svpOyfmQKuWpHLjgy4cdK"
begin = "1994"
origin = "Montréal"

tags = ["post-rock", "instrumental", "ambient", "experimental-rock", "ca", "90s"]
