format = 1
generated = true
name = "Jarvis Cocker"
mbid = "38550441-d437-4aff-867e-e79bf0c04142"
spotify = "13W7XLRXdWeLmIu9vacE1w"
begin = "1963"
origin = "Sheffield"

tags = ["britpop", "uk"]

tops = [
  "The Tearjerker Returns",
  "Aline",
  "Magic Works",
  "Do the Hippogriff",
  "Fantastic Mr. Fox AKA Petey's Song",
]

links = [
  { to = "pulp", type = "member" },
  { to = "keren-ann", type = "similar" },
  { to = "nouvelle-vague", type = "similar" },
  { to = "the-liminanas", type = "similar" },
  { to = "nick-cave-and-the-bad-seeds", type = "similar" },
]
