format = 1
generated = true
name = "La Ruda Salska"
mbid = "db6107e1-f692-453a-ab0e-4566faaba298"
spotify = "5wLQgAe9uO150K07T2MYvl"
begin = "1993"
end = "2012"
origin = "Saumur"

tags = ["ska", "pop", "punk", "fr", "90s"]

tops = [
  "L'art de la joie",
  "Le bruit du bang",
  "L'instinct du meilleur - Live",
  "Orange",
  "Trianon",
]
