format = 1
generated = true
name = "Marvin Gaye"
mbid = "afdb7919-059d-43c1-b668-ba1d265e7e42"
spotify = "3koiLjNrgRTNbOwViDipeA"
begin = "1939"
end = "1984"
origin = "Washington, D.C."

tags = ["soul", "funk", "smooth-soul", "motown", "us"]

tops = [
  "Sexual Healing",
  "I Heard It Through The Grapevine",
  "What's Going On",
  "Distant Lover",
  "Let's Get It On",
]

links = [
  { to = "stevie-wonder", type = "similar" },
  { to = "the-temptations", type = "similar" },
  { to = "al-green", type = "similar" },
  { to = "aretha-franklin", type = "similar" },
]
