format = 1
generated = true
name = "Vladimír Václavek"
mbid = "10855f12-f619-400b-87f5-6c9b13d39481"
begin = "1959"

tags = ["cz"]

tops = [
  "Zeleny Vinecek",
  "Sto Iet",
  "Vzpomínka",
  "Huljet",
  "Sirka v Iouzi",
]
